# Generated by Django 5.2.5 on 2025-08-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_supplier_email_supplier_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
