# Generated by Django 5.2.5 on 2025-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image_product_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
