# Generated by Django 5.2.5 on 2025-08-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stockentry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
