# Generated by Django 5.2.5 on 2025-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stockentry_initial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
