# Generated by Django 5.2.5 on 2025-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_stockentry_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='received_date',
            field=models.DateTimeField(null=True),
        ),
    ]
