# Generated by Django 5.2.5 on 2025-08-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_stockentry_initial_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('SALE', 'Sale'), ('DAMAGE', 'Damage'), ('RETURN', 'Return to supplier'), ('ADJUST', 'Inventory adjust'), ('OTHER', 'Other')], default='SALE', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='main.product')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.stockentry')),
            ],
        ),
    ]
