# Generated by Django 5.2.5 on 2025-08-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stockwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='expiry_notified',
            field=models.BooleanField(default=False),
        ),
    ]
