# Generated by Django 5.2.5 on 2025-08-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_stockentry_received_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockentry',
            old_name='received_date',
            new_name='received_at',
        ),
    ]
