# Generated by Django 5.2.5 on 2025-08-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_received_date_stockentry_received_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='received_at',
        ),
    ]
