# Generated by Django 5.2.5 on 2025-08-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_stockentry_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
